In [5]:
import numpy as np

n = np.array([1,2,3])
print(n)

print(type(n))

[1 2 3]
<class 'numpy.ndarray'>


In [39]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype = 'int32')
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print(a[1][0])

4


In [26]:
a.ndim

2

In [27]:
a.shape

(3, 3)

In [31]:
a.dtype , a.size, a.nbytes

(dtype('int32'), 9, 36)

In [37]:
a[:,2] = np.array([1,2,3])# a[r,c]
print(a)

[[1 2 1]
 [4 5 2]
 [7 8 3]]


In [40]:
a[0,0:2]

array([1, 2], dtype=int32)

In [45]:
l = [1,2,3,4]
print(l[0:3:2])

[1, 3]


In [48]:
a = np.array([[[1,2],[3,4]], [[5,6], [7,8]]], dtype = 'int16')
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [50]:
a[0,1,1], a.itemsize

(np.int16(4), 2)

In [52]:
np.zeros((1,2))


array([[0., 0.]])

In [53]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
np.full((2,3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [60]:
import random

np.random.rand(2,3)


array([[0.20132158, 0.70532271, 0.84878338],
       [0.64908255, 0.08892555, 0.35114152]])

In [62]:
np.random.randint(7, size=(2,3), dtype = 'int16')

array([[5, 2, 0],
       [6, 4, 5]], dtype=int16)

In [64]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
y = np.array([[1,2,4]])
print(y)
x = np.repeat(y, 3, axis = 0)
print(x)

[[1 2 4]]
[[1 2 4]
 [1 2 4]
 [1 2 4]]


### Project Testing 

In [77]:
z = np.array([[1,1,1,1,1]], dtype = 'int16')
new_z = np.repeat(z,5,axis = 0)
print(new_z)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [79]:
new_z[1:4, 1:4] = 0
print(new_z)
new_z[2,2] = 9


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [80]:
print(new_z)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [83]:
a = np.array([1,2,3])
b = a
b[0] = 2
print(a)
b = a.copy() # deep copy completely different memory location 
b[1] = 9
print(a)

[2 2 3]
[2 2 3]


In [96]:
l = list((1,2,3,4))
print(l)
# l1 = l # deep copy 
l1 = [1,2,3,4]
l1[2] = 5
print(l)

print(id(l), id(l1))

[1, 2, 3, 4]
[1, 2, 3, 4]
2490555284992 2490555882880


In [97]:
s1 = "Kamran"
s2 =  "Kamran"
print(id(s1), id(s2))
s1 = "hello"
print(id(s1), id(s2))

2490545737424 2490545737424
2490167219504 2490545737424


In [99]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a*b)
print(a/b)
print(a**b)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [101]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [110]:
a = np.array([1,2,3])
b = np.full((1,3), 2)

# np.matmul(a,b)

In [111]:
np.vstack([a,b])

array([[1, 2, 3],
       [2, 2, 2]])

In [121]:
## Input from the text files 

filename = np.genfromtxt('data.txt', delimiter = ',')
filename = filename.astype('int16')
print(filename)

print(filename[0].itemsize)

[1 2 3 4 5 6]
2
